---
name: Load Parameters
description: Load parameters for the build job

outputs:
  build_matrix:
    description: Build matrix
    value: ${{ steps.matrix.outputs.build_matrix }}

runs:
  using: "composite"
  steps:
    - name: Set the Build Matrix
      id: matrix
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const path = require('path');
          const ConfigPath = path.join(process.env.GITHUB_WORKSPACE, 'ci', 'CONFIG.json');
          let Config;
          try {
            if (!fs.existsSync(ConfigPath)) {
              core.setFailed(`CONFIG.json not found at ${ConfigPath}`);
              return;
            }
            Config = JSON.parse(fs.readFileSync(ConfigPath, 'utf-8'));
          } catch (err) {
            core.setFailed(`Failed to load or parse CONFIG.json: ${err.message}`);
            return;
          }
          // Build matrix: os, kernel, firmware
          const build_matrix = Object.values(Config).map(obj => Object.fromEntries(Object.entries(obj)));
          core.setOutput('build_matrix', JSON.stringify(build_matrix));
          console.log("Build Matrix:", build_matrix);
          // summary
          const md = [
            '# Repositories to build',
            '',
            '```json',
            JSON.stringify(build_matrix, null, 2),
            '```'
          ].join('\n');
          fs.appendFileSync(process.env.GITHUB_STEP_SUMMARY, md + '\n');
